### ISSUE TITLE
ทำ Animation Sprite ตัวเอก

### ISSUE THREAD

**Issue by GNOGz** [GNOGz/KohRangHangRak#1]
ที่ต้องการ(หนักหน่อยนะเพื่อน T-T)
movement :
-วิ่ง
-ย่อ
-โจมตี
-เก็บของ
-กระโดด
-โดนดาเมจ
-ตาย

**Comment by sakdipatr** [comment]
ทำแล้วนะจ๊ะเพื่อน (อัป Animation ลงในไดรฟ์ให้ละนะ)
